from __future__ import annotations

import json
import mimetypes
import os
from datetime import datetime, timezone
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlparse

import psycopg
from psycopg.rows import dict_row


ROOT = Path(__file__).resolve().parent
DATABASE_URL = os.environ.get("DATABASE_URL")
DEFAULT_CATEGORIES = (("Staples", "#8569C8"), ("Fruit & Vege", "#4EA960"), ("Snacks", "#D69B1F"), ("Household", "#CC5757"), ("Drinks", "#59A7CC"))


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def json_default(value: object) -> str:
    if isinstance(value, datetime):
        return value.isoformat()
    raise TypeError(f"Cannot serialize {type(value).__name__}")


class Database:
    def __init__(self) -> None:
        if not DATABASE_URL:
            raise RuntimeError("DATABASE_URL is required")
        self.connection = psycopg.connect(DATABASE_URL, row_factory=dict_row)

    def execute(self, query: str, params: tuple = ()):
        return self.connection.execute(query.replace("?", "%s"), params)

    def executemany(self, query: str, params) -> None:
        with self.connection.cursor() as cursor:
            cursor.executemany(query.replace("?", "%s"), params)

    def executescript(self, script: str) -> None:
        for statement in script.split(";"):
            if statement.strip():
                self.connection.execute(statement)

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback) -> None:
        if exc_type is None:
            self.connection.commit()
        else:
            self.connection.rollback()
        self.connection.close()


def connection() -> Database:
    return Database()


POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    quantity TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    purchased_at TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    quantity TEXT NOT NULL DEFAULT '',
    purchased_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    color TEXT NOT NULL DEFAULT '#747B75',
    position INTEGER NOT NULL DEFAULT 0,
    is_staple BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS idx_items_active ON items(category, id DESC) WHERE purchased_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_purchases_name ON purchases(LOWER(name), purchased_at DESC);
CREATE INDEX IF NOT EXISTS idx_purchases_recent ON purchases(purchased_at DESC);
"""


def init_db() -> None:
    with connection() as db:
        db.executescript(POSTGRES_SCHEMA)
        db.executemany(
            "INSERT INTO categories(name, color, position, is_staple) VALUES (?, ?, ?, ?) ON CONFLICT (name) DO NOTHING",
            ((name, color, position, name == "Staples") for position, (name, color) in enumerate(DEFAULT_CATEGORIES)),
        )
        db.execute("""INSERT INTO categories(name, color, position)
            SELECT DISTINCT source.category, '#747B75', 100 FROM (
                SELECT category FROM items UNION SELECT category FROM purchases
            ) source WHERE NOT EXISTS (SELECT 1 FROM categories c WHERE c.name = source.category)""")


def clean_text(value: object, limit: int) -> str:
    return " ".join(str(value or "").split())[:limit]


def valid_color(value: object) -> str:
    color = str(value or "").strip().upper()
    if len(color) != 7 or not color.startswith("#") or any(c not in "0123456789ABCDEF" for c in color[1:]):
        raise ValueError("Choose a valid category colour.")
    return color


def category_exists(db: Database, name: str) -> bool:
    return db.execute("SELECT 1 FROM categories WHERE name = ?", (name,)).fetchone() is not None


def state() -> dict:
    with connection() as db:
        categories = db.execute("SELECT id, name, color FROM categories ORDER BY position, id").fetchall()
        items = db.execute(
            """SELECT i.*,
                      (SELECT MAX(p.purchased_at) FROM purchases p
                       WHERE LOWER(p.name) = LOWER(i.name)) AS last_purchased
               FROM items i ORDER BY (i.purchased_at IS NOT NULL), i.id DESC"""
        ).fetchall()
        recent = db.execute(
            """SELECT name, category, quantity, purchased_at, purchase_count
               FROM (
                   SELECT name, category, quantity, purchased_at,
                          COUNT(*) OVER (PARTITION BY LOWER(name)) AS purchase_count,
                          ROW_NUMBER() OVER (
                              PARTITION BY LOWER(name) ORDER BY purchased_at DESC, id DESC
                          ) AS row_number
                   FROM purchases
               ) ranked
               WHERE row_number = 1
               ORDER BY purchased_at DESC LIMIT 30"""
        ).fetchall()
    return {"categories": [dict(x) for x in categories], "items": [dict(x) for x in items], "recent": [dict(x) for x in recent]}


class Handler(BaseHTTPRequestHandler):
    server_version = "Pantrify/1.0"

    def log_message(self, fmt: str, *args: object) -> None:
        print(f"[{self.log_date_time_string()}] {fmt % args}")

    def send_json(self, data: object, status: int = HTTPStatus.OK) -> None:
        body = json.dumps(data, default=json_default).encode()
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body)

    def read_json(self) -> dict:
        length = int(self.headers.get("Content-Length", "0"))
        return json.loads(self.rfile.read(length) or b"{}")

    def serve_file(self, relative: str) -> None:
        path = (ROOT / relative).resolve()
        if ROOT not in path.parents or not path.is_file():
            self.send_error(HTTPStatus.NOT_FOUND)
            return
        body = path.read_bytes()
        self.send_response(HTTPStatus.OK)
        self.send_header("Content-Type", mimetypes.guess_type(path.name)[0] or "application/octet-stream")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self) -> None:
        path = urlparse(self.path).path
        if path == "/api/state":
            self.send_json(state())
        elif path in ("/", "/index.html"):
            self.serve_file("static/index.html")
        elif path.startswith("/static/"):
            self.serve_file(path.lstrip("/"))
        else:
            self.send_error(HTTPStatus.NOT_FOUND)

    def do_POST(self) -> None:
        path = urlparse(self.path).path
        try:
            data = self.read_json()
            if path == "/api/items":
                name = clean_text(data.get("name"), 120)
                category = clean_text(data.get("category"), 80)
                quantity = clean_text(data.get("quantity"), 40)
                with connection() as db:
                    if not name or not category_exists(db, category):
                        return self.send_json({"error": "A product and valid category are required."}, 400)
                    existing = db.execute(
                        "SELECT id FROM items WHERE purchased_at IS NULL AND LOWER(name) = LOWER(?)", (name,)
                    ).fetchone()
                    if existing:
                        return self.send_json({"error": "That item is already on the list."}, 409)
                    db.execute(
                        "INSERT INTO items(name, category, quantity, created_at) VALUES (?, ?, ?, ?)",
                        (name[:120], category, quantity, now_iso()),
                    )
                self.send_json(state(), 201)
            elif path == "/api/categories":
                name = clean_text(data.get("name"), 80)
                color = valid_color(data.get("color"))
                if not name:
                    return self.send_json({"error": "Category name is required."}, 400)
                with connection() as db:
                    position = db.execute("SELECT COALESCE(MAX(position), -1) + 1 AS next FROM categories").fetchone()["next"]
                    db.execute("INSERT INTO categories(name, color, position) VALUES (?, ?, ?)", (name, color, position))
                self.send_json(state(), 201)
            elif path == "/api/items/new-list":
                with connection() as db:
                    staple = db.execute("SELECT name FROM categories WHERE is_staple ORDER BY id LIMIT 1").fetchone()
                    staple_name = staple["name"] if staple else "Staples"
                    current_staples = db.execute(
                        "SELECT name, quantity FROM items WHERE category = ? ORDER BY id DESC",
                        (staple_name,),
                    ).fetchall()
                    purchased_staples = db.execute(
                        "SELECT name, quantity FROM purchases WHERE category = ? ORDER BY purchased_at DESC",
                        (staple_name,),
                    ).fetchall()
                    recurring = {}
                    for staple in (*current_staples, *purchased_staples):
                        recurring.setdefault(staple["name"].casefold(), (staple["name"], staple["quantity"]))
                    db.execute("DELETE FROM items")
                    db.executemany(
                        "INSERT INTO items(name, category, quantity, created_at) VALUES (?, ?, ?, ?)",
                        ((name, staple_name, quantity, now_iso()) for name, quantity in recurring.values()),
                    )
                self.send_json(state())
            elif path == "/api/items/clear-purchased":
                with connection() as db:
                    db.execute("DELETE FROM items WHERE purchased_at IS NOT NULL")
                self.send_json(state())
            elif path.startswith("/api/items/") and path.endswith("/purchase"):
                item_id = int(path.split("/")[3])
                purchased_at = now_iso()
                with connection() as db:
                    item = db.execute("SELECT * FROM items WHERE id = ? AND purchased_at IS NULL", (item_id,)).fetchone()
                    if not item:
                        return self.send_json({"error": "Item not found."}, 404)
                    db.execute("UPDATE items SET purchased_at = ? WHERE id = ?", (purchased_at, item_id))
                    db.execute(
                        "INSERT INTO purchases(item_id, name, category, quantity, purchased_at) VALUES (?, ?, ?, ?, ?)",
                        (item_id, item["name"], item["category"], item["quantity"], purchased_at),
                    )
                self.send_json(state())
            elif path == "/api/repeat":
                name = str(data.get("name", "")).strip()
                with connection() as db:
                    previous = db.execute(
                        "SELECT name, category, quantity FROM purchases WHERE LOWER(name) = LOWER(?) ORDER BY purchased_at DESC LIMIT 1",
                        (name,),
                    ).fetchone()
                    if not previous:
                        return self.send_json({"error": "Purchase not found."}, 404)
                    exists = db.execute(
                        "SELECT 1 FROM items WHERE purchased_at IS NULL AND LOWER(name) = LOWER(?)", (name,)
                    ).fetchone()
                    if not exists:
                        db.execute(
                            "INSERT INTO items(name, category, quantity, created_at) VALUES (?, ?, ?, ?)",
                            (previous["name"], previous["category"], previous["quantity"], now_iso()),
                        )
                self.send_json(state(), 201)
            elif path.startswith("/api/items/"):
                item_id = int(path.split("/")[3])
                name, category = clean_text(data.get("name"), 120), clean_text(data.get("category"), 80)
                quantity = clean_text(data.get("quantity"), 40)
                with connection() as db:
                    if not name or not category_exists(db, category):
                        return self.send_json({"error": "A product and valid category are required."}, 400)
                    item = db.execute("SELECT purchased_at FROM items WHERE id = ?", (item_id,)).fetchone()
                    if not item:
                        return self.send_json({"error": "Item not found."}, 404)
                    duplicate = db.execute("SELECT 1 FROM items WHERE id <> ? AND purchased_at IS NULL AND LOWER(name) = LOWER(?)", (item_id, name)).fetchone()
                    if duplicate and item["purchased_at"] is None:
                        return self.send_json({"error": "That item is already on the list."}, 409)
                    db.execute("UPDATE items SET name = ?, category = ?, quantity = ? WHERE id = ?", (name, category, quantity, item_id))
                self.send_json(state())
            elif path.startswith("/api/categories/"):
                category_id = int(path.split("/")[3])
                name, color = clean_text(data.get("name"), 80), valid_color(data.get("color"))
                if not name:
                    return self.send_json({"error": "Category name is required."}, 400)
                with connection() as db:
                    old = db.execute("SELECT name FROM categories WHERE id = ?", (category_id,)).fetchone()
                    if not old:
                        return self.send_json({"error": "Category not found."}, 404)
                    db.execute("UPDATE categories SET name = ?, color = ? WHERE id = ?", (name, color, category_id))
                    if old["name"] != name:
                        db.execute("UPDATE items SET category = ? WHERE category = ?", (name, old["name"]))
                        db.execute("UPDATE purchases SET category = ? WHERE category = ?", (name, old["name"]))
                self.send_json(state())
            else:
                self.send_json({"error": "Not found."}, 404)
        except (ValueError, json.JSONDecodeError) as exc:
            self.send_json({"error": str(exc) or "Invalid request."}, 400)
        except psycopg.Error as exc:
            print(f"Database error: {exc}")
            if getattr(exc, "sqlstate", None) == "23505":
                self.send_json({"error": "That name is already in use."}, 409)
            else:
                self.send_json({"error": "Database error."}, 500)


if __name__ == "__main__":
    init_db()
    port = int(os.environ.get("PORT", "8000"))
    server = ThreadingHTTPServer(("0.0.0.0", port), Handler)
    print(f"Pantrify is running at http://localhost:{port}")
    print("Database: PostgreSQL")
    print("Open the same address using this computer's local IP to share it on your Wi-Fi.")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nStopping Pantrify.")
    finally:
        server.server_close()
